### login
post http://localhost:8000/user/signup
Content-Type: application/json

{
    "email": “test@naver”,
    "userimage": ””,
    "channel": ”테스트채널”,
    "password": ”123456”,
    "confirmPassword": ”123456”,
}
